export const PATH_NAME = {
    HOMEPAGE: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    NEW_PASSWORD: "/forgot-password/new-password",
    OTP_AUTHENTICATION: "/forgot-password/otp-auth",
    ITEMS: "/items",
    ABOUT_US: "/about-us",
    CONTACT_US: "/contact-us",
    DASH_BOARD: "/dashboard",
    PRODUCTS: "/products",
    ORDERS: "/orders",
    CUSTOMERS: "/customers",
}
