export const PATH_NAME = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    NEW_PASSWORD: "/forgot-password/new-password",
    PRODUCT_DETAILS: "/product-details/:id",
    ITEMS: "/items",
    ABOUT_US: "/about-us",
    CONTACT_US: "/contact-us",
    DASH_BOARD: "/admin/dashboard",
    ADMIN_PRODUCTS: "/admin/products",
    ADMIN_CATEGORY: "/admin/category",
    ADMIN_ORDERS: "/admin/orders",
    ADMIN_CUSTOMERS: "/admin/customers",
    CUSTOMERS: "/customers",
    SHOPPING_CARTS: "/shopping-cart",
    PAYMENT: "/payment",
    ACCOUNT: "/account",
    ORDER: "/account/order",
    PAYMENT_SUCCESS: "/payment-success",
    PAYMENT_FAILED: "/payment-failed",
}