export const PATH_NAME = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    NEW_PASSWORD: "/forgot-password/new-password",
    PRODUCT_DETAILS: "/product-details",
    ITEMS: "/items",
    ABOUT_US: "/about-us",
    CONTACT_US: "/contact-us",
    DASH_BOARD: "/admin/dashboard",
    ADMIN_PRODUCTS: "/admin/products",
    ADMIN_ORDERS: "/admin/orders",
    ADMIN_CUSTOMERS: "/admin/customers",
}
